### ISSUE TITLE
PCA build dictionary EOFError: Ran out of input

### ISSUE THREAD

**Issue by joeoct93** [Huang-yihao/FakePolisher#1]
I attempted to do PCA reconstruction following the instructions. I used CelebA as the real images.
python PCA_data_preprocess.py --input_image_folder "path to real image folder" --save_path "path to save processed images.pkl" --image_size_width 224  --image_size_height 224

python PCA_build_dictionary.py --input_file_path "pkl file which has processed data" --number 10000 --PCA_component 1000 --model_path "path to save PCA model.pkl" --image_size_width  224 --image_size_height 224

However, I keep getting this error:
Namespace(input_file_path='/mnt/c/Project/HI/FakePolisher1/preprocessed/realA/realPCA.pkl', number=10000, PCA_component=3000, model_path='/mnt/c/Project/HI/FakePolisher1/preprocessed/PCAmodel.pkl', image_size_width=224, image_size_height=224)
Traceback (most recent call last):
  File "/mnt/c/Project/HI/FakePolisher1/PCA_build_dictionary.py", line 55, in <module>
    analysis(input_file_path, number, model_path, pca_number, image_size_width, image_size_height)
  File "/mnt/c/Project/HI/FakePolisher1/PCA_build_dictionary.py", line 10, in analysis
    face_array = pickle.load(f)
EOFError: Ran out of input
![image](https://user-images.githubusercontent.com/105055206/177028927-4cc7376f-2c73-4c44-aca5-e3d0fb55a351.png)

I can't figure out how to get through this part. is there something I'm doing wrong? (changing the PCA components number didn't do anything)

**Comment by Huang-yihao** [comment]
Probably the "/mnt/c/Project/HI/FakePolisher1/preprocessed/realA/realPCA.pkl" is empty, please check it

**Comment by joeoct93** [comment]
Hmm... I'm not sure what I did wrong even now. However, when I tried it on a different computer, I managed to complete this part. I think somehow, depending on setting or GPU or whatever, something happened, because the realPCA.pkl created on the old computer was around 10GB, while the realPCA.pkl created on the new computer (with better GPU) is around 29GB.
