### ISSUE TITLE
PCA Polish image error

### ISSUE THREAD

**Issue by joeoct93** [Huang-yihao/FakePolisher#2]
While I got past the previous error, I ran into another error when trying to use the PCA Polish. I preprocessed the fake images fine, but in the PCA Polish, I ran into the following error.

(Fakepolisher) cchoi1022@DESKTOP-Q470KUQ:/mnt/c/Project/HI/fakep$ python PCA_polish_image.py --input_fake_path /mnt/c/Project/HI/fakep/preprocessed/styleGANcelebAPCA.pkl --PCA_model_path /mnt/c/Project/HI/fakep/model/PCAmodel.pkl --save_path /mnt/c/Project/HI/fakep/reconstructed  --image_size_width 224 --image_size_height 224
Namespace(input_fake_path='/mnt/c/Project/HI/fakep/preprocessed/styleGANcelebAPCA.pkl', PCA_model_path='/mnt/c/Project/HI/fakep/model/PCAmodel.pkl', save_path='/mnt/c/Project/HI/fakep/reconstructed', show_result=False, image_size_width=224, image_size_height=224)
Traceback (most recent call last):
  File "/mnt/c/Project/HI/fakep/PCA_polish_image.py", line 90, in <module>
    transform(input_fake_path,PCA_model_path,show_result,save_path,image_size_width,image_size_height)
  File "/mnt/c/Project/HI/fakep/PCA_polish_image.py", line 14, in transform
    am, fil, ril = joblib.load(f)
ValueError: too many values to unpack (expected 3)

![image](https://user-images.githubusercontent.com/105055206/177477173-87ab4552-a8b0-4211-81e2-92affb1d61a4.png)

I haven't changed anything from the instructions except having input fake path be preprocessed fake image pkl (because apparently it can't be a directory like it claims it should be). What am I  doing wrong?

**Comment by Huang-yihao** [comment]
Sorry, it is my mistake. 
Please see below. Let me explain the code.
![image](https://user-images.githubusercontent.com/16575311/178104289-ae1048a0-b087-4acd-9c34-4b26038261de.png)

The am and ril (in blue box) in line 14 are not used in the code. Only fil is used in the code. fil means the fake images.
So here the code should be corrected as

![image](https://user-images.githubusercontent.com/16575311/178104514-1b2d37ad-890d-4238-86a4-d551e60efb54.png)

I have changed the code.
Please note that the fake image path should end with the left forward slash. For example, /mnt/mfs/xxx/

**Comment by ZXMMD** [comment]
![image](https://user-images.githubusercontent.com/46393405/189062479-de2733cd-01e9-4f6e-a3bc-a8e9d3175cdf.png)

fake_image_list  is defined in line 15, why is it set to an empty list on line 21?

**Comment by ZXMMD** [comment]
Can you make the file pca_model_224_10000.pkl public? Or send it to my email zxmmd@qq.com, due to insufficient experimental equipment, I cannot reproduce your experimental results well.
